### ISSUE TITLE
Please bump major version when dropping support for older node.js versions

### ISSUE THREAD

**Issue by carno** [sindresorhus/semver-truncate#4]
Hello, in Your recent commit You started to use string templates which were introduced AFAIR in node v4.
While doing so You only bumped patch version which results in breaking packages which use Your module for people using node 0.12.

Example when trying to install flow-bin:
```javascript
[16:41:34]> flow-bin@0.23.0 postinstall /ephemeral/teamcity/euca-10-254-205-85.eucalyptus.internal-01/work/946aa8e38ea48cb1/src/node_modules/@my_module/builder/node_modules/flow-bin
[16:41:34]> node lib/install.js
[16:41:34]
[16:41:34]/ephemeral/teamcity/euca-10-254-205-85.eucalyptus.internal-01/work/946aa8e38ea48cb1/src/node_modules/@my_module/builder/node_modules/flow-bin/node_modules/bin-wrapper/node_modules/bin-version-check/node_modules/semver-truncate/index.js:12
[16:41:34]		throw new Error(`Version ${version} is not valid semver`);
[16:41:34]		                ^
[16:41:34]SyntaxError: Unexpected token ILLEGAL
[16:41:34]    at exports.runInThisContext (vm.js:73:16)
[16:41:34]    at Module._compile (module.js:443:25)
[16:41:34]    at Object.Module._extensions..js (module.js:478:10)
[16:41:34]    at Module.load (module.js:355:32)
[16:41:34]    at Function.Module._load (module.js:310:12)
[16:41:34]    at Module.require (module.js:365:17)
[16:41:34]    at require (module.js:384:17)
[16:41:34]    at Object.<anonymous> (/ephemeral/teamcity/euca-10-254-205-85.eucalyptus.internal-01/work/946aa8e38ea48cb1/src/node_modules/@my_module/builder/node_modules/flow-bin/node_modules/bin-wrapper/node_modules/bin-version-check/index.js:4:22)
[16:41:34]    at Module._compile (module.js:460:26)
[16:41:34]    at Object.Module._extensions..js (module.js:478:10)
```

Can You please publish version `1.1.2` without string templates and bump major version for future development/releases which drops support for older node.js versions?

**Comment by sindresorhus** [comment]
It was an accident and fixed right away. Sorry.
